### ISSUE TITLE
Dependency issues on installation...

### ISSUE THREAD

**Issue by jeisenlo** [fullcube/loopback-component-access-groups#13]
The following is the error I receive while trying to install loopback-component-access-groups just after installing StrongLoop Loopback and creating a brand new LoopBack API project. 

Jamess-MacBook-Pro:loopback-access-groups jameseisenlohr$ npm install --save loopback-component-access-groups
npm WARN peerDependencies The peer dependency loopback@>=2.25.0 included from loopback-component-access-groups will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "loopback-component-access-groups"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package loopback@3.0.0-alpha.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer loopback-component-access-groups@0.2.0 wants loopback@>=2.25.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jameseisenlohr/Tests/loopback-access-groups/npm-debug.log
Jamess-MacBook-Pro:loopback-access-groups jameseisenlohr$ 

Any suggestions and help would be appreciated.

**Comment by mrfelton** [comment]
@jeisenlo it looks like you are trying to use in conjunction with loopback 3.0.0-alpha.3, which it does not currently support (it hasn't been tested with this at all yet). Unless you know loopback very very well, I'd suggest you work with the stable 2.x branch of loopback.

**Comment by jeisenlo** [comment]
Thank you, Tom!
